[target.'cfg(all(target_arch = "arm", target_os = "none"))']
#runner = "./flash_firmware.sh"  # DFU flashing only - no debugging
runner = "probe-rs run --chip STM32F429VI --speed 4600"  # Enable debugging with probe-rs

[build]
target = "thumbv7em-none-eabi"

[env]
DEFMT_LOG = "info"
